inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

require:
  - rubocop-rails



AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
